"""
QuantForge Core Event System

Event-driven architecture for the backtesting engine.
All communication between components happens via events through the EventBus.
"""



from abc import ABC, abstractmethod

from dataclasses import dataclass, field

from datetime import datetime

from enum import Enum, auto

from typing import Any, Callable, Dict, List, Optional, Set

import heapq

import functools





class EventType(Enum):

    """Enumeration of all event types in the system."""

    MARKET_DATA = auto()

    SIGNAL = auto()

    ORDER = auto()

    FILL = auto()

    PORTFOLIO_UPDATE = auto()

    BARS_UPDATE = auto()





@functools.total_ordering

@dataclass

class Event:

    """Base class for all events in the system."""

    timestamp: datetime

    event_type: EventType



    def __post_init__(self):

        if not isinstance(self.timestamp, datetime):

            raise TypeError(f"Timestamp must be datetime, got {type(self.timestamp)}")



    def __lt__(self, other: 'Event') -> bool:

        """Enable comparison for priority queue ordering."""

        if not isinstance(other, Event):

            return NotImplemented

        return self.timestamp < other.timestamp



    def __eq__(self, other: object) -> bool:

        if not isinstance(other, Event):

            return NotImplemented

        return self.timestamp == other.timestamp and self.event_type == other.event_type





@dataclass

class MarketDataEvent(Event):

    """
    Market data bar event (OHLCV).

    Attributes:
        symbol: Trading symbol (e.g., 'AAPL')
        open_price: Opening price for the bar
        high_price: High price for the bar
        low_price: Low price for the bar
        close_price: Closing price for the bar (used for most calculations)
        volume: Trading volume
        adjusted_close: Split/dividend adjusted close price
        vwap: Volume Weighted Average Price (optional)
    """

    symbol: str

    open_price: float

    high_price: float

    low_price: float

    close_price: float

    volume: int

    adjusted_close: float

    vwap: float = 0.0



    def __post_init__(self):

        if self.event_type is None:

            self.event_type = EventType.MARKET_DATA





        if not self.symbol:

            raise ValueError("Symbol cannot be empty")

        if self.high_price < self.low_price:

            raise ValueError(f"High price ({self.high_price}) cannot be lower than low price ({self.low_price})")

        if self.volume < 0:

            raise ValueError(f"Volume cannot be negative: {self.volume}")



        epsilon = 1e-9

        if self.open_price > self.high_price + epsilon or self.open_price < self.low_price - epsilon:



             pass

        if self.close_price > self.high_price + epsilon or self.close_price < self.low_price - epsilon:

             pass



    @property

    def range(self) -> float:

        """Trading range for the period (High - Low)."""

        return self.high_price - self.low_price



    @property

    def close(self) -> float:

        """Alias for close_price to match some strategies."""

        return self.close_price





@dataclass

class SignalEvent(Event):

    """
    Trading signal generated by a strategy.

    Signal strength is continuous in [-1, 1] where:
        -1.0 = Full short signal
         0.0 = Neutral/no signal
        +1.0 = Full long signal

    Mathematical basis:
        Signal represents the expected risk-adjusted return direction.
        Position sizing converts signal to actual dollar exposure.

    Attributes:
        symbol: Trading symbol
        signal: Signal strength [-1, 1]
        strategy_name: Name of the generating strategy
        confidence: Confidence level [0, 1]
        metadata: Additional strategy-specific data
    """

    symbol: str

    signal: float

    strategy_name: str

    confidence: float = 1.0

    metadata: Dict[str, Any] = field(default_factory=dict)



    def __post_init__(self):

        if self.event_type is None:

            self.event_type = EventType.SIGNAL





        if not (-1.0 <= self.signal <= 1.0):

             raise ValueError(f"Signal must be between -1 and 1, got {self.signal}")

        if not (0.0 <= self.confidence <= 1.0):

             raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")













class OrderType(Enum):

    """Types of orders supported by the execution engine."""

    MARKET = auto()

    LIMIT = auto()

    STOP = auto()

    STOP_LIMIT = auto()





@dataclass

class OrderEvent(Event):

    """
    Order request to be executed by the execution simulator.

    Attributes:
        symbol: Trading symbol
        quantity: Number of shares (positive=buy, negative=sell)
        order_type: Type of order
        limit_price: Price limit for LIMIT orders
        stop_price: Trigger price for STOP orders
        strategy_name: Strategy that generated this order
    """

    symbol: str

    quantity: int

    order_type: OrderType = OrderType.MARKET

    limit_price: Optional[float] = None

    stop_price: Optional[float] = None

    strategy_name: str = ""



    def __post_init__(self):

        if self.event_type is None:

            self.event_type = EventType.ORDER





        if self.quantity == 0:

            raise ValueError("Order quantity cannot be zero")





        if isinstance(self.order_type, str):

            try:

                self.order_type = OrderType[self.order_type.upper()]

            except KeyError:

                raise ValueError(f"order_type must be one of {[t.name for t in OrderType]}")

        elif not isinstance(self.order_type, OrderType):

             raise ValueError(f"order_type must be OrderType enum, got {type(self.order_type)}")



        if self.order_type == OrderType.LIMIT and self.limit_price is None:

            raise ValueError("Limit price required for LIMIT orders")



    @property

    def is_buy(self) -> bool:

        return self.quantity > 0



    @property

    def is_sell(self) -> bool:

        return self.quantity < 0



    @property

    def abs_quantity(self) -> int:

        return abs(self.quantity)





@dataclass

class FillEvent(Event):

    """
    Order fill notification from the execution simulator.

    Includes all transaction costs for accurate P&L calculation.

    Attributes:
        symbol: Trading symbol
        quantity: Filled quantity
        fill_price: Average fill price
        commission: Commission paid
        slippage: Slippage cost (difference from expected fill)
        order_id: Reference to original order
    """

    symbol: str

    quantity: int

    fill_price: float

    commission: float = 0.0

    slippage: float = 0.0

    order_id: Optional[str] = None



    @property

    def total_cost(self) -> float:

        """Total transaction cost including commission and slippage."""

        return self.commission + abs(self.slippage * self.quantity)



    @property

    def direction(self) -> int:

        """Returns 1 for buy, -1 for sell."""

        return 1 if self.quantity > 0 else -1



    @property

    def notional_value(self) -> float:

        """Total notional value of the fill (quantity * price)."""

        return abs(self.quantity * self.fill_price)



    @property

    def is_buy(self) -> bool:

        return self.quantity > 0



    @property

    def is_sell(self) -> bool:

        return self.quantity < 0



    def __post_init__(self):

        if self.event_type is None:

            self.event_type = EventType.FILL





        if self.quantity == 0:

            raise ValueError("Fill quantity cannot be zero")

        if self.fill_price < 0:

            raise ValueError(f"Fill price cannot be negative: {self.fill_price}")

        if self.commission < 0:

            raise ValueError(f"Commission cannot be negative: {self.commission}")





@dataclass

class PortfolioUpdateEvent(Event):

    """Portfolio state update event."""

    positions: Dict[str, int] = field(default_factory=dict)

    cash: float = 0.0

    equity: float = 0.0



    def __post_init__(self):

        if self.event_type is None:

            self.event_type = EventType.PORTFOLIO_UPDATE





class EventBus:

    """
    Priority queue-based event bus for the event-driven architecture.

    The EventBus is the central nervous system of the backtester.
    All components communicate by publishing events and subscribing to event types.

    Events are processed in chronological order using a priority queue (min-heap),
    ensuring no look-ahead bias in backtests.

    Example:
        >>> bus = EventBus()
        >>> bus.subscribe(EventType.MARKET_DATA, my_strategy.on_market_data)
        >>> bus.publish(MarketDataEvent(...))
        >>> bus.run()  # Process all queued events
    """



    def __init__(self):

        self._queue: List[Event] = []

        self._handlers: Dict[EventType, List[Callable[[Event], None]]] = {}

        self._event_count = 0



    def subscribe(self, event_type: EventType, handler: Callable[[Event], None]) -> None:

        """
        Subscribe a handler function to a specific event type.

        Args:
            event_type: The type of event to listen for
            handler: Function to call when event of this type is published
        """

        if event_type not in self._handlers:

            self._handlers[event_type] = []

        self._handlers[event_type].append(handler)



    def unsubscribe(self, event_type: EventType, handler: Callable[[Event], None]) -> bool:

        """
        Remove a handler from an event type subscription.

        Args:
            event_type: The event type to unsubscribe from
            handler: The handler function to remove

        Returns:
            True if handler was found and removed, False otherwise
        """

        if event_type in self._handlers and handler in self._handlers[event_type]:

            self._handlers[event_type].remove(handler)

            return True

        return False



    def publish(self, event: Event) -> None:

        """
        Publish an event to the bus. The event will be queued for processing.

        Args:
            event: The event to publish
        """

        heapq.heappush(self._queue, event)

        self._event_count += 1



    def process_next(self) -> bool:

        """
        Process the next event in the queue.

        Returns:
            True if an event was processed, False if queue is empty
        """

        if not self._queue:

            return False



        event = heapq.heappop(self._queue)

        handlers = self._handlers.get(event.event_type, [])



        for handler in handlers:

            handler(event)



        return True



    def run(self, max_events: int = -1) -> int:

        """
        Process events in the queue.

        Args:
            max_events: Maximum number of events to process. -1 for all.

        Returns:
            Number of events processed
        """

        count = 0

        while (max_events == -1 or count < max_events) and self.process_next():

            count += 1

        return count



    def peek_next(self) -> Optional[Event]:

        """
        Peek at the next event without removing it.

        Returns:
            The next event, or None if queue is empty
        """

        return self._queue[0] if self._queue else None



    def clear(self) -> None:

        """Clear all events from the queue."""

        self._queue.clear()



    def reset(self) -> None:

        """Reset the event bus (alias for clear)."""

        self.clear()

        self._handlers.clear()

        self._event_count = 0



    @property

    def is_empty(self) -> bool:

        """Check if the event queue is empty."""

        return len(self._queue) == 0



    @property

    def queue_size(self) -> int:

        """Return the current number of events in the queue."""

        return len(self._queue)



    def get_event_count(self) -> int:

        """Return the total number of events published since creation."""

        return self._event_count



    @property

    def total_events_processed(self) -> int:

        """Property alias for get_event_count() to satisfy tests."""

        return self._event_count



    def get_subscriber_count(self, event_type: EventType) -> int:

        """Return the number of subscribers for a given event type."""

        return len(self._handlers.get(event_type, []))







__all__ = [

    'EventType',

    'Event',

    'MarketDataEvent',

    'SignalEvent',

    'OrderType',

    'OrderEvent',

    'FillEvent',

    'PortfolioUpdateEvent',

    'EventBus',

]
