"""
Event System - The heart of event-driven backtesting
Events flow: Market -> Signal -> Order -> Fill
"""



from abc import ABC

from dataclasses import dataclass, field

from datetime import datetime

from enum import Enum, auto

from typing import Optional, Dict, Any

import numpy as np





class EventType(Enum):

    """Event types in the trading system"""

    MARKET = auto()

    SIGNAL = auto()

    ORDER = auto()

    FILL = auto()

    RISK = auto()

    PORTFOLIO_UPDATE = auto()





class Event(ABC):

    """Base class for all events"""



    def __init__(self, timestamp: Optional[datetime] = None):

        self.type: EventType = EventType.MARKET

        self.timestamp = timestamp or datetime.now()



    def __repr__(self):

        return f"{self.__class__.__name__}(timestamp={self.timestamp})"





@dataclass

class MarketEvent(Event):

    """
    Market data event - triggered when new market data arrives
    """

    symbol: str = ""

    open: float = 0.0

    high: float = 0.0

    low: float = 0.0

    close: float = 0.0

    volume: float = 0.0

    timestamp: datetime = field(default_factory=datetime.now)

    timeframe: str = "1d"

    additional_data: Dict[str, Any] = field(default_factory=dict)



    def __post_init__(self):

        self.type = EventType.MARKET



    @property

    def vwap(self) -> float:

        """Volume-weighted average price for this bar"""

        return (self.high + self.low + self.close) / 3



    @property

    def range(self) -> float:

        """Price range for this bar"""

        return self.high - self.low



    @property

    def body(self) -> float:

        """Candle body size"""

        return abs(self.close - self.open)



    def to_dict(self) -> Dict[str, Any]:

        return {

            'symbol': self.symbol,

            'open': self.open,

            'high': self.high,

            'low': self.low,

            'close': self.close,

            'volume': self.volume,

            'timestamp': self.timestamp.isoformat(),

            'timeframe': self.timeframe,

        }





@dataclass

class SignalEvent(Event):

    """
    Trading signal event - generated by strategies
    """

    symbol: str = ""

    signal_type: str = ""

    strength: float = 1.0

    strategy_id: str = ""

    timestamp: datetime = field(default_factory=datetime.now)

    price: float = 0.0

    metadata: Dict[str, Any] = field(default_factory=dict)

    confidence: float = 0.5



    def __post_init__(self):

        self.type = EventType.SIGNAL



    @property

    def is_long(self) -> bool:

        return self.signal_type.upper() in ['LONG', 'BUY', 'ENTRY_LONG']



    @property

    def is_short(self) -> bool:

        return self.signal_type.upper() in ['SHORT', 'SELL', 'ENTRY_SHORT']



    @property

    def is_exit(self) -> bool:

        return self.signal_type.upper() in ['EXIT', 'CLOSE', 'FLAT']





@dataclass

class OrderEvent(Event):

    """
    Order event - generated by portfolio/risk manager
    """

    symbol: str = ""

    order_type: str = "MARKET"

    direction: str = ""

    quantity: float = 0.0

    price: float = 0.0

    stop_price: float = 0.0

    timestamp: datetime = field(default_factory=datetime.now)

    order_id: str = ""

    strategy_id: str = ""

    time_in_force: str = "GTC"



    def __post_init__(self):

        self.type = EventType.ORDER

        if not self.order_id:

            self.order_id = f"ORD_{self.timestamp.strftime('%Y%m%d%H%M%S')}_{np.random.randint(10000)}"





@dataclass

class FillEvent(Event):

    """
    Fill event - generated by execution handler when order is filled
    """

    symbol: str = ""

    direction: str = ""

    quantity: float = 0.0

    fill_price: float = 0.0

    commission: float = 0.0

    timestamp: datetime = field(default_factory=datetime.now)

    order_id: str = ""

    exchange: str = "SIMULATED"

    slippage: float = 0.0



    def __post_init__(self):

        self.type = EventType.FILL



    @property

    def cost(self) -> float:

        """Total cost of the fill including commission"""

        return self.fill_price * self.quantity + self.commission



    @property

    def notional(self) -> float:

        """Notional value of the fill"""

        return self.fill_price * self.quantity





@dataclass

class RiskEvent(Event):

    """
    Risk management event - triggered by risk checks
    """

    risk_type: str = ""

    severity: str = ""

    message: str = ""

    timestamp: datetime = field(default_factory=datetime.now)

    action_required: bool = False

    metadata: Dict[str, Any] = field(default_factory=dict)



    def __post_init__(self):

        self.type = EventType.RISK





@dataclass

class PortfolioUpdateEvent(Event):

    """
    Portfolio update event - triggered after fills
    """

    timestamp: datetime = field(default_factory=datetime.now)

    positions: Dict[str, Any] = field(default_factory=dict)

    cash: float = 0.0

    equity: float = 0.0



    def __post_init__(self):

        self.type = EventType.PORTFOLIO_UPDATE
