// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder - run `make proto` to generate actual file

package proto

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tick represents a single market data tick
type Tick struct {
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Symbol    string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price     float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Volume    float64                `protobuf:"fixed64,4,opt,name=volume,proto3" json:"volume,omitempty"`
	Bid       float64                `protobuf:"fixed64,5,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask       float64                `protobuf:"fixed64,6,opt,name=ask,proto3" json:"ask,omitempty"`
	Sequence  uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

// Placeholder for other message types
type Bar struct{}
type OrderBook struct{}
type Trade struct{}
type Signal struct{}
type Order struct{}
type Position struct{}
type Portfolio struct{}

// Service interfaces
type QuantServiceServer interface{}
type QuantServiceClient interface{}